name: Atualizar Jogos Diariamente

on:
  schedule:
    # Roda todos os dias à meia-noite (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite rodar manualmente clicando num botão no GitHub

permissions:
  contents: write

jobs:
  update-games:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install axios

    - name: Rodar script de download
      run: node scripts/update-db.js

    - name: Verificar mudanças e Enviar (Commit & Push)
      run: |
        git config --global user.name 'Atualizador Automático'
        git config --global user.email 'actions@github.com'
        git add data/games.json data/categories.json
        # Só faz o commit se houver mudanças
        git diff --quiet && git diff --staged --quiet || (git commit -m "Atualização automática dos jogos [skip ci]" && git push)
